[pubmed]
term = "Brevundimonas diminuta case reports[pt] AND free full text[Filter]"
email = "joheli@gmx.net"
keyword = "Bervundimonas diminuta" # optional
retmax = 50
batch_size = 25

[database]
sqlite_path = "mudpeter1.db"

[fulltext]
enabled = true
prefer_pmc = true
use_pdf = true
max_chars = 500000
